Stage1
AntonKosmovskyXB/jet-start pull request #1
Opened 2021-04-22 17:13 UTC by AntonKosmovskyXB

Stage1 task completed

2021-04-23 06:05 UTC, AlexeyXB requested changes

2021-04-23 06:05 UTC, AlexeyXB commented on sources/views/contacts.js
> +					template: "<span class='webix_icon wxi-user'></span> #value#",
Здесь не хватает информации о компании, судя по макету

2021-04-23 06:05 UTC, AlexeyXB commented on sources/views/popup.js
> +							}
Время не восстанавливается после перезагрузки страницы

2021-04-23 06:46 UTC, AlexeyXB requested changes

2021-04-23 06:46 UTC, AlexeyXB commented on sources/views/popup.js
> +			this.$$("header").setValues({headerTemplate});
Лучше в таком случае вынести кнопку и header в отдельные переменные и потом к ним обращаться, чем каждый раз вызывать функцию $$.

2021-04-23 07:58 UTC, AlexeyXB approved these changes

2021-04-23 16:27 UTC, HelgaListopad requested changes
Баг:
- открой редактор существующей activity
- не закрывая окно, нажми на trash в таблице, удали редактируемую запись
- нажми в окне Save

Вылетит ошибка.
Чтобы избежать этого
- окно может быть модальным,
- или при нажатии на trash ты можешь закрыть редактор

2021-04-23 16:27 UTC, HelgaListopad commented on sources/models/activities.js
> +			const savedTime = webix.Date.strToDate("%h:%i");
Все эти парсеры было бы красивее вынести как константы рядом с activities. Каждый раз вызывать их по-новой довольно избыточно, так как
- `$init`/`$save` вызываются для каждой отдельной записи
- `dateToStr` и `strToDate` возвращают метод форматирования, который можно подготовить один раз заранее.

2021-04-23 16:27 UTC, HelgaListopad commented on sources/views/contactInfo.js
> +					<div class="status align-center">Status ID: #StatusID#</div>
У тебя есть коллекция statuses, откуда можно подтянуть текст для статуса

2021-04-23 16:27 UTC, HelgaListopad commented on sources/views/contactInfo.js
> +					<span class='webix_icon mdi mdi-email'></span><span>#Email#</span> <br><br>
Если какого-то поля в записи нет, лучше это предусмотреть в виде `${ obj.Email ? obj.Email : "Unknown" }` (подразумевая, что темплейт задан функцией)

2021-04-23 16:27 UTC, HelgaListopad commented on sources/views/popup.js
> +			this.form.clear();
Эти же методы повторяются в клике по Cancel - их (вместе с clearValidation) можно вынести в отдельный метод и не повторять эту запись.

2021-04-23 16:27 UTC, HelgaListopad commented on sources/views/popup.js
> +								format: webix.i18n.dateFormatStr
Стоило бы добавить валидацию и на дату - задавать активность без неё будет немного странно.

2021-04-24 11:53 UTC, AntonKosmovskyXB commented on sources/models/activities.js
> +			const savedTime = webix.Date.strToDate("%h:%i");
Исправлено

2021-04-24 11:53 UTC, AntonKosmovskyXB commented on sources/views/contactInfo.js
> +					<div class="status align-center">Status ID: #StatusID#</div>
Исправлено

2021-04-24 11:53 UTC, AntonKosmovskyXB commented on sources/views/contactInfo.js
> +					<span class='webix_icon mdi mdi-email'></span><span>#Email#</span> <br><br>
Исправлено

2021-04-24 11:54 UTC, AntonKosmovskyXB commented on sources/views/popup.js
> +								format: webix.i18n.dateFormatStr
Исправлено

2021-04-24 12:42 UTC, AntonKosmovskyXB commented on sources/views/popup.js
> +			this.form.clear();
Исправлено

2021-04-24 13:52 UTC, HelgaListopad requested changes

2021-04-24 13:52 UTC, HelgaListopad commented on sources/views/activities.js
> +							this.popup.hide();
`closePopup`

2021-04-24 14:30 UTC, AntonKosmovskyXB commented on sources/views/activities.js
> +							this.popup.hide();
Извиняюсь, не заметил.
Исправлено

2021-04-24 14:44 UTC, HelgaListopad approved these changes

2021-04-24 14:44 UTC, merged