Stage2
AntonKosmovskyXB/jet-start pull request #2
Opened 2021-04-29 05:24 UTC by AntonKosmovskyXB

2021-04-29 12:11 UTC, AlexeyXB requested changes

2021-04-29 12:11 UTC, AlexeyXB commented on sources/models/contacts.js
>  		}
Тут при обновлении коллекции нет обновления value, что не позволяет обновить информацию о имени и фамилии в листе контактов

2021-04-29 12:18 UTC, AlexeyXB requested changes

2021-04-29 12:18 UTC, AlexeyXB commented on sources/views/contacts.js
> +					this.setUrlParam(this.list.getSelectedId());
Если я начинаю редактирование информации о контакте у меня есть доступ к списку контактов и кнопке add contact. И тут обычно ожидается, что если я нажму на другой контакт или на кнопку добавления должно что-то произойти. 
Если я уже что-то начал редактировать и нажал на другой контакт или add contact, то должен показаться confirm, который говорит, что у меня есть несохраненные данные и выбор действий. Отмена - значит я возвращаюсь к редактированию, продолжить - отменяю все что не сохранено и заполняю форму новыми данными, либо очищаю форму.

2021-04-29 12:18 UTC, AlexeyXB commented on sources/views/contactsForm.js
> +			view: "form",
Layout формы странно разошелся

2021-04-29 17:42 UTC, AlexeyXB commented on sources/views/contacts.js
> +					this.setUrlParam(this.list.getSelectedId());
Попробуй добавить onBeforeSelect

2021-04-29 17:42 UTC, AlexeyXB commented on sources/views/contactsForm.js
> +			view: "form",
Форма по прежнему странно выглядит

2021-04-29 18:07 UTC, AlexeyXB requested changes

2021-04-29 18:07 UTC, AlexeyXB commented on sources/views/contactsForm.js
> +						},
Так получается, что у тебя номер может содержать не только цифры. Надо бы проверку добавить.

2021-04-29 18:07 UTC, AlexeyXB commented on sources/views/contactsForm.js
> +						this.saveContact();
После сохранения нового контакта нужно закрыть форму и отобразить детали о новом контакте.

2021-04-29 18:07 UTC, AlexeyXB commented on sources/views/contactsForm.js
> +							this.closeForm();
При закрытии формы, если это add new contact, нужно выбрать первый контакт в листе для отображения детальной информации.

2021-04-30 10:27 UTC, AlexeyXB requested changes

2021-04-30 10:27 UTC, AlexeyXB commented on sources/views/contactsForm.js
> +							labelWidth: 100
Лучше создать константу для ширины и использовать ее, чтобы потом было проще изменить ширину сразу всем.

2021-04-30 10:53 UTC, AlexeyXB requested changes

2021-04-30 10:53 UTC, AlexeyXB commented on sources/views/contactsForm.js
> +		if (id && contacts.exists(id)) {
ClearValidation просится

2021-04-30 10:59 UTC, AlexeyXB requested changes

2021-04-30 10:59 UTC, AlexeyXB commented on sources/views/contacts.js
> +		contactsForm.form.clear();
Т.к. в updateForm ты уже делаешь очистку, то здесь она ни к чему

2021-04-30 11:11 UTC, AlexeyXB approved these changes

2021-04-30 13:42 UTC, HelgaListopad requested changes
Взаимодействие между JetViews построено на прямых обращениях к другим вьюшкам - так не пойдёт. Пересмотри эту логику, пожалуйста.

2021-04-30 13:42 UTC, HelgaListopad commented on sources/views/contactInfo.js
> +		this.contactsView = this.getParentView();
Тот самый случай, когда нужно обойтись без getParentView.
JetView должны быть как можно больше изолированы друг от друга, то есть методы листа должны вызываться в его же классе.
Для этого уместно использовать app-level события, передавая из одной вьюшки (формы) в другую (contacts) о том, что пора что-то сделать.

2021-04-30 13:42 UTC, HelgaListopad commented on sources/views/contactInfo.js
> +									contactsFormView.updateForm(currentId);
Это слишком хитрый переход в соседнее вью (get parent => get another subview), и в Jet так делать не стоит практически никогда - слишком нестабильное решение, зависящее от иеррархии вьюшек.
Форма может брать ID при своём открытии через getParam.

2021-04-30 13:42 UTC, HelgaListopad commented on sources/views/contacts.js
> +					if (contactsFormView.form && contactsFormView.form.isDirty()) {
Это очень хорошее предостережение, но реализовать его лучше так, как я рассказывала сегодня на созвоне - через событие, а не через прямой доступ к другой вьюшке с помощью getSubView

2021-04-30 13:42 UTC, HelgaListopad commented on sources/views/contactsForm.js
> +							labelWidth
Общие свойства можно перенести в https://docs.webix.com/api__link__ui.form_elementsconfig_config.html
Так они будут примененыт ко всем элементам формы. Если у какого-то виджета те же параметры будут отличаться - его собственные свойства будут приоритетнее.

2021-04-30 13:42 UTC, HelgaListopad commented on sources/views/contactsForm.js
> +		this.contactsList = this.getParentView().list;
Та же история с нежелательным доступом к соседним JetView.

2021-04-30 13:42 UTC, HelgaListopad commented on sources/views/contactsForm.js
> +				this.contactsList.select(newItem.id);
В этот момент селектить ещё рано. 
На клиенте новый контакт добавляется с рандомной айдишкой, а настоящая приходит уже с сервера. У тебя в Contacts есть обработчик `dp.attachEvent("onAfterSave")`, и вот достаточно использовать только его.

Альтернатива - изменить логику и использовать `waitSave`, но это уже просто комментарий о другой возможности, а не призыв переделать именно на это.

2021-04-30 17:04 UTC, AntonKosmovskyXB commented on sources/views/contactInfo.js
> +		this.contactsView = this.getParentView();
Исправил через app-level events

2021-04-30 17:04 UTC, AntonKosmovskyXB commented on sources/views/contactInfo.js
> +									contactsFormView.updateForm(currentId);
Исправил через app-level events

2021-04-30 17:04 UTC, AntonKosmovskyXB commented on sources/views/contactsForm.js
> +							labelWidth
Исправлено

2021-04-30 17:05 UTC, AntonKosmovskyXB commented on sources/views/contactsForm.js
> +		this.contactsList = this.getParentView().list;
Исправил через app-level events

2021-04-30 17:05 UTC, AntonKosmovskyXB commented on sources/views/contactsForm.js
> +				this.contactsList.select(newItem.id);
Исправлено

2021-04-30 18:37 UTC, HelgaListopad commented on sources/views/contactInfo.js
> +									contactsFormView.updateForm(currentId);
Ну-у, не совсем.)
Ты решил передавать с помощью события целую форму - это немного не то. 
Кроме того, сейчас у тебя частенько падает переход между контактами после edit/add, так как есть шанс не сбросивть `this.form` на Contacts - и на этом твой вызов isDirty начнёт падать. 

Эта фраза годится для любого модуля:
> JetView должны быть как можно больше изолированы друг от друга, то есть методы ~~листа~~ формы должны вызываться в её же классе.

Иными словами, `this.form` тебе на Contacts вовсе не нужен. 
Чем тебе нужно обмениваться между листом и формой в параметрах событий - так это двумя параметрами: `isDirty` и `id`.
С id всё почти ок - но нужно будет протестировать после описанных ниже изменений. Скорее всего, можно упростить, но здесь лучше вносить изменения по порядку.

Что касается именно isDirty
Тут можно самотоятельно написать схему, похожую на ту, что ты используешь на готовых onBefore- событиях. То есть вызываем `callEvent`, если он возвращает `false` - прерываем действие по умолчанию, показываем confirm.

По умолчанию `callEvent` всегда возвращает `true`. 
Если хотя бы один обработчик события вернул `false` - `callEvent` вернёт то же самое. 

Как это применять: например, в onBeforeSelect листа (+ похожая проверка для кнопки)
```js
if (this.app.callEvent("isFormSaved", []) === false) {
	webix.confirm({ text: /* ... */ }).then(() => {
		/* ... */
		this.setUrlParam(id);   // не селект, иначе можно зациклить confirm
	});
	return false;
}
```
В форме, соответственно,
```js
this.on(this.app, "isFormSaved", () => {
	return !this.form.isDirty();  // инвертируем, чтобы получить false
})
```
Таким образом, если форма сейчас существует на странице - вернётся результат проверки. 
Если формы нет - значение по умолчанию (`true`).

2021-05-01 19:38 UTC, HelgaListopad requested changes
Переход по контактам и фильтрация их activities
- выбери контакт
- отфильтруй его activities
- выбери другой контакт - фильтры не сбросятся/не будут применены для новых данных

Лібо нужно сбросить фильтр, либо вызвать filterByAll, чтобы снова применить его

2021-05-01 19:38 UTC, HelgaListopad commented on sources/views/contacts.js
> +				template: `<div class="contacts-list"><span class='webix_icon wxi-user'></span> <div class='short-info'>
Хотелось бы, чтобы тут отображалась аватарка юзера, если она есть

2021-05-01 19:38 UTC, HelgaListopad commented on sources/views/contactsForm.js
> +					this.form.clearValidation();
Лучше убрать и оставить все поля отмеченными, пока они не пройдкт валидацию. 
Валидация перерисовывает инпут - как следствие, фокус сбрасывается. Юзеру придётся два раза кликнуть на инпут, чтобы начать печатать в нём текст, а это грустно.)

2021-05-01 19:38 UTC, HelgaListopad commented on sources/views/popup.js
> +			this.app.callEvent("onDatatableChange", [this.getParentView().activitiesTable.getState()]);
Хоть здесь и используется `getParentView`, это легальное решение и я не буду считать это за проблему, но тут важно озвучить, почему. 
Это попап, инициализированный через `this.ui` на какое-то конкретное view и привязанный только к нёму. 
Parent однозначный, поэтому и метод вполне уместен.

2021-05-01 20:55 UTC, HelgaListopad approved these changes

2021-05-01 20:56 UTC, merged