Stage3
AntonKosmovskyXB/jet-start pull request #3
Opened 2021-05-05 09:47 UTC by AntonKosmovskyXB

2021-05-05 10:43 UTC, AlexeyXB requested changes

2021-05-05 10:43 UTC, AlexeyXB commented on sources/views/contactInfo.js
> +				}
Тут лучше сразу данные брать из `currentStatus`, а не из `statuses.getItem(currentUser.StatusID`

2021-05-05 10:43 UTC, AlexeyXB commented on sources/views/contactsForm.js
> +					status = +obj.StatusID;
Все же лучше `Number.parseInt` или `parseInt`.

2021-05-05 10:43 UTC, AlexeyXB commented on sources/views/popup.js
> +					TypeID: id => activitiesTypes.data.order.includes(+id)
Все же лучше Number.parseInt или parseInt.

2021-05-05 15:31 UTC, AlexeyXB requested changes

2021-05-05 15:31 UTC, AlexeyXB commented on sources/models/icons.js
> +	data: [
Не хватает уже существующих иконок, как минимум для чата и обеда

2021-05-05 15:31 UTC, AlexeyXB commented on sources/locales/ru.js
> +	Cancel: "Закончить",
Поменяй, пожалуйста, на что-то более подходящее.

2021-05-05 15:31 UTC, AlexeyXB commented on sources/views/contacts.js
>  						webix.confirm({
Confirm у тебя не полностью переведен

2021-05-05 16:55 UTC, AlexeyXB requested changes

2021-05-05 16:55 UTC, AlexeyXB commented on sources/models/icons.js
> -			icon: "webix_icon mdi mdi-phone"
А почему ты `phone` удалил?

2021-05-05 18:15 UTC, AlexeyXB approved these changes

2021-05-06 08:57 UTC, HelgaListopad requested changes
Я упустила это в прошлом ревью (и это мой косяк), но есть баг, который нужно исправить

- фото контакта в листе не отображается [правильно](https://www.w3docs.com/snippets/html/how-to-display-base64-images-in-html.html)
- и не загружается на сервер как поле Photo контакта при сохранении данных из формы

2021-05-06 08:57 UTC, HelgaListopad commented on sources/views/activities.js
> +			return date.getDate() === obj.DueDate.getDate();
[getDate](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Date/getDate) возвращает только число, не учитывая месяц/год
Для такой проверки это не годится, так как проверку могут пройти две совершенно разные даты

2021-05-06 08:57 UTC, HelgaListopad commented on sources/views/activities.js
> +			return date.getDate() === obj.DueDate.getDate();
То же самое для Tomorrow

2021-05-06 08:57 UTC, HelgaListopad commented on sources/views/activities.js
> +			return date.getMonth() === obj.DueDate.getMonth();
И тут не учитывается год

2021-05-06 08:57 UTC, HelgaListopad commented on sources/views/contactInfo.js
> +				const currentStatus = statuses.getItem(currentUser.StatusID);
Здесь ты меняешь напрямую исходный объект данных - это не очень хорошо, даже если новые свойства больше нигде не используются
Сделай здесь копию, и меняй/загружай в темплейт уже её

2021-05-06 08:57 UTC, HelgaListopad commented on sources/locales/ru.js
> +	Edit: "Исправить",
Всё-таки по смыслу тут "изменить", а не "исправить" - исправление подразумевает, что есть какая-то ошибка

2021-05-06 08:57 UTC, HelgaListopad commented on sources/views/popup.js
> +					ContactID: id => contacts.data.order.includes(parseInt(id)),
Напрямую к order обращаться, как правило, не стоит, а конкретно тут можно использовать [exists](https://docs.webix.com/api__link__datacollection_exists.html)

2021-05-06 10:24 UTC, HelgaListopad approved these changes

2021-05-06 10:26 UTC, merged